version: 2

jobs:
 build:
   machine: true
   working_directory: ~/workspace

   steps:
     - checkout

     - run:
         name: Build docker image
         command: |
           docker build -t codesamsung/tizen-studio-flutter .

     - run:
         name: Push to docker hub
         command: |
           docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
           docker push codesamsung/tizen-studio-flutter:latest
           docker tag codesamsung/tizen-studio-flutter:latest codesamsung/tizen-studio-flutter:${CIRCLE_SHA1:0:6}
           docker push codesamsung/tizen-studio-flutter:${CIRCLE_SHA1:0:6}

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              only: main
